# main
spring:
  profiles:
    active: test # 기본 환경 선택
# common setting
---
spring.profiles: common
server:
  port: 8085
  error.whitelabel.enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    add-properties: false
  freemarker:
    cache: false
  jpa:
    open-in-view: false
  servlet:
    multipart.max-file-size: 50MB
    multipart.max-request-size: 50MB
# local 환경
---
spring:
  profiles: local
  profiles.include: common, ssl
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yappian_local?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
      username: yappian_local
      password: test1234!
  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show-sql: true
# local에서 test
---
spring.profiles: test
spring.profiles.include: common #, ssl

spring:
  h2:
    console:
      enabled: true
      path: /h2/
      settings:
#        trace: true
        web-allow-others: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:yappian;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;MVCC=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    data: classpath:init.sql
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
#logging:
#  level:
#    org.springframework.web.client: DEBUG
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
# production 환경
---
spring.profiles: prod
spring.profiles.include: real-db, common
#logging:
#  file: ./log/prod